"""add unique constraint for table event

Revision ID: f1b72b7d3d64
Revises: 003b733b24fc
Create Date: 2026-08-22 21:35:29.574739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b72b7d3d64'
down_revision: Union[str, Sequence[str], None] = '003b733b24fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_booking_table_event', 'bookings', ['table_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_booking_table_event', 'bookings', type_='unique')
    # ### end Alembic commands ###
